### ISSUE TITLE
[BUG] Plugin fails to load using Java 16

### ISSUE THREAD

**Issue by Thornbush42** [bloodmc/GriefDefender#400] opened 2021-05-17 21:40 UTC
- **Versions**
Paper: #692
GriefDefender: 1.5.10
LuckPerms: 5.3.39
Java: 16

- **Describe the bug**
Plugin fails to start when using Java 16

- **Steps to reproduce the behavior**
Install and run Paper with Java 16, watch the plugin not be able to load.

- **Expected behavior**
Plugin loads as it should and has done using Java 11

- **Screenshots**
Console error: https://pastebin.com/n6WeSQHZ

**Comment by Thornbush42** [comment] 2021-05-19 21:07
Found a temporary workaround:

Add "--illegal-access=permit" as a start-up flag

**Comment by Sleinous** [comment] 2021-06-11 14:03
Same issue here, was prepping our server for 1.17 and noticed this is the only plugin that failed initial prep tests
Thanks for the workaround

`[13:55:01] [Server thread/INFO]: [GriefDefender] Enabling GriefDefender v1.5.10
[13:55:01] [Server thread/INFO]: [GriefDefender] Loading libraries...
[13:55:01] [Server thread/ERROR]: Error occurred while enabling GriefDefender v1.5.10 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.griefdefender.GDBootstrap.injectRelocatorDeps(GDBootstrap.java:150) ~[?:?]
        at com.griefdefender.GDBootstrap.onEnable(GDBootstrap.java:131) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-562]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-562]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-562]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-562]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-562]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:252) ~[patched_1.16.5.jar:git-Paper-562]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-562]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-562]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @3ff7ce05
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
        at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
        at com.griefdefender.util.BootstrapUtil.<clinit>(BootstrapUtil.java:42) ~[?:?]
        ... 11 more
[13:55:01] [Server thread/INFO]: [GriefDefender] Disabling GriefDefender v1.5.10
[13:55:01] [Server thread/INFO]: [GriefDefender] Enabling GriefDefender v1.5.10
[13:55:01] [Server thread/INFO]: [GriefDefender] Loading libraries...
[13:55:01] [Server thread/ERROR]: Error occurred while enabling GriefDefender v1.5.10 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.griefdefender.GDBootstrap.injectRelocatorDeps(GDBootstrap.java:150) ~[?:?]
        at com.griefdefender.GDBootstrap.onEnable(GDBootstrap.java:131) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-562]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-562]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-562]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-562]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-562]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:252) ~[patched_1.16.5.jar:git-Paper-562]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-562]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-562]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @3ff7ce05
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
        at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
        at com.griefdefender.util.BootstrapUtil.<clinit>(BootstrapUtil.java:42) ~[?:?]
        ... 11 more
`

**Comment by Sleinous** [comment] 2021-06-17 20:04
Workaround is unstable, server crashes daily as a result. Rolling back to java11 & will have to find another anti-grief if not fixed by the time paper 1.17 is out.

**Comment by kencinder** [comment] 2021-06-19 06:05
Java 16 is not supported and simply expecting any plugin to work and support it quickly is absurd. Java 16 support is coming as well with GD 2.0.

**Closed as completed by kencinder** 2021-06-19 06:05 UTC
