### ISSUE TITLE
Cannot chat after clicking '+' in accessors, /claiminfo

### ISSUE THREAD

**Issue by CJcool06** [bloodmc/GriefDefender#178] opened 2020-04-17 15:06 UTC
SpongeForge: 1.12.2-2838-7.2.0
GD: 1.2.6 B2

Going into /claiminfo, clicking accessors, then clicking '+' puts the player in an infinite state of being unable to chat. Relogging doesn't fix the issue.

I'd suggest a timeout of some amount of time.

**Comment by DrWurzeli** [comment] 2020-04-17 16:42
cant reproduce on paper with gd 1.2.6B4. everything works fine.

but +1 for timeout, since there is none for now or option to input `cancel` to stop chat capturing.
maybe use the already existing command-input-idle-timeout from config.

**Comment by Brycey92** [comment] 2020-04-17 23:57
He appears to be using SpongeForge, not Paper, so the bug may only be in the Sponge version of GD.

**Comment by CJcool06** [comment] 2020-04-19 07:45
Turns out if the player doesn't have a certain permission, they get stuck and can't get out. It was fixed by giving them the permission. However, a way to cancel it without having the permission would still be helpful.

**Comment by RobinWhitfield** [comment] 2020-04-20 08:57
I had this or potentially a very similar issue this morning.

I logged on and every time I tried to chat it brought up the claim permissions page.
I had full admin perms and server op. Neither logging in and out, removing admin perms and server op perms and then reloading gd fixed the issue so in the end I just bounced the server.

There's a possibility that the last thing I was doing yesterday was looking at permissions/adding or removing people in the gui but I couldn't figure out what was going on at the time.

Running GD 1.2.6 on Paper 165 and Luckperms 5.0.130

**Comment by DrWurzeli** [comment] 2020-04-20 09:01
"full admin perms and server op"
this does not mean anything since griefdefender.user.chat.capture is a user permission.
assign it and you should be fine :)

**Comment by RobinWhitfield** [comment] 2020-04-20 09:06
Sorry, should have been clearer.

All of the time I had griefdefender.user.* from our default group.

What I tried was removing griefdefender.admin.* and server op to no avail.

I'll see if I can reproduce the issue.

**Comment by RobinWhitfield** [comment] 2020-04-20 09:16
OK, that didn't take long.

I can reproduce as originally described by @CJcool06 

I do /claiminfo, click through to add an accessor/builder/container/manager, then click [+] to add someone, then I log out.

Upon logging back in, I can't chat and I'm just brought back to the page to add a user/group.

To get out of the stuck position I seem to be able to type in a valid entry (group <name> / player <name>,  although it doesn't appear to add that group/player to any of the claim permissions groups) or /claiminfo, claim permissions, [+], Cancel/group <name>/player <name>.

**Comment by RobinWhitfield** [comment] 2020-04-21 09:48
As it seems similar but not identical to what was originally raised, should I raise this as a new issue or leave it where it is?

**Comment by SnowBlitzz** [comment] 2020-04-29 15:35
Here's a video one of our players provided. https://youtu.be/2vvaRACDbeE

**Closed** 2020-04-30 22:29 UTC
