### ISSUE TITLE
[BUG] /claimban items missing most protections

### ISSUE THREAD

**Issue by Brycey92** [bloodmc/GriefDefender#415] opened 2021-08-30 03:37 UTC
- **Versions**
Spigot/Paper/Sponge: SF 1.12.2-2838-7.3.1-RC4112
GriefDefender: 2.0.1-DEV9
LuckPerms: 5.3.64

- **Describe the bug**

/claimban only blocks interact-item-primary and interact-item-secondary, when it should block everything. Also, in global.conf, all blocks and items banned are inserted into the items category.

- **Steps to reproduce the behavior**

1. Hold an item
2. /claimban hand (or manually set the item ID in global.conf if it's configured for ID replacement. In this case, I'm using ic2:blast_furnace
3. /cfdebug (or skip this step)
4. Craft the item, drop it, pick it up, place and break it if it's a block, open it and mess around inside its inventory if it has one
5. Left click and right click the item in empty air

- **Expected behavior**

None of the interactions in step 4 should work, but they do. kencinder says all interactions should be banned, so not just those mentioned in step 4. Step 5 correctly prints that the item is banned. Also, banned blocks and items in global.conf should be split between blocks and items categories as appropriate.

- **GDDEBUG**

https://griefdefender.github.io/debug/?yomYKohw2s

- **Screenshots**

**Comment by Brycey92** [comment] 2021-08-30 21:36
An update: manually moving a block from the items category to the blocks category results in interact-block-primary and interact-block-secondary being denied, but still none of the others such as item-pickup and inventory-click.

**Comment by bloodmc** [comment] 2021-09-02 04:36
I am unable to reproduce this issue with vanilla items/blocks. Provide the ban section in `global.conf`

Update: Issue is in sponge but works fine in bukkit. I'll fix...

**Comment by bloodmc** [comment] 2021-09-02 05:15
Fixed in 2.0.1 DEV13

**Closed as completed by bloodmc** 2021-09-02 05:15 UTC
