### ISSUE TITLE
[BUG] The amount not displayed correctly

### ISSUE THREAD

**Issue by gstio86** [bloodmc/GriefDefender#377] opened 2021-03-05 02:42 UTC
- **Versions**
Spigot/Paper/Sponge: Recommended 7.3.0
GriefDefender: GriefDefender 1.5.11-DEV 
LuckPerms: luckperms 5.2.76

- **Describe the bug**

![image](https://user-images.githubusercontent.com/74390539/110058500-5edfe100-7d9d-11eb-9667-4da0e626a21f.png)
When I execute /buyclaimblocks 100, the output message `You now have 0 available claim blocks.`
The amount is wrong should be the complete quantity after purchase

```
    int bonusTotal = playerData.getBonusClaimBlocks();
    playerData.setBonusClaimBlocks(bonusTotal + blockCount.intValue());
    int newTotal = playerData.getRemainingClaimBlocks() + blockCount;
    Component message = (GriefDefenderPlugin.getInstance()).messageData.getMessage("economy-block-purchase-confirmation", (Map)ImmutableMap.of(
          "amount", Double.valueOf(totalCost), 
          "balance", Integer.valueOf(newTotal)));
```

By the way, you can add a placeholder for the quantity purchased?
like this 
```
"blockCount" , blockCount;
```
![image](https://user-images.githubusercontent.com/74390539/110059553-66a08500-7d9f-11eb-8fa9-583696208377.png)

**Comment by bloodmc** [comment] 2021-04-09 14:18
Issue is caused by call being async and sometimes not completing in time to show proper result. Will be fixed next development build.

**Comment by bloodmc** [comment] 2021-12-05 02:50
This was fixed in earlier releases.

**Closed by bloodmc** 2021-12-05 02:50 UTC
