### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by LucidAPs** [bloodmc/GriefDefender#417] opened 2021-08-31 09:49 UTC
Server version git-Purpur-1363 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 286984c on ver/1.17.1)
GriefDefender version 2.0.0
Luckperms version build 5.3.64

GriefDefender is the worst performer out of all my plugins.
Spark sampler --only-ticks-above 200 (go to sources tab)
https://spark.lucko.me/d7df931CI3
Normal spark sampler (go to sources tab)
https://spark.lucko.me/CuCBuOGJ1g

GriefDefender is taking 4.30% of the servers tick and is also raising luckperms usages because of the lookups to an other 2.30%
for grand total of 6.00% of the servers whole tick.

Player count on my server is 70-90 players.
Main Config
https://nekobin.com/dodikagera

**Comment by LucidAPs** [comment] 2021-09-01 09:10
The WorldSaveEvent seems to be a big part of the performance issue aswell.
![image](https://user-images.githubusercontent.com/42933023/131644734-aaa08aaa-72e4-40f3-903f-3f320c7a0b89.png)
https://timings.pl3x.net/?id=224539f2548c4c33a42e3d95b505886f

**Comment by LucidAPs** [comment] 2021-09-01 15:30
It seems that GD is doing disk IO (saves?lookups?) on the main thread. 
![image](https://user-images.githubusercontent.com/42933023/131701323-f6280b9c-1ffa-4cae-b8a7-497adad11a38.png)
That seems to be the cause for most of the "lag spikes" I recorded here. The code responsible that should be changed into async is here I believe? https://github.com/bloodmc/GriefDefender/blob/e281231d874d78def944e748f6b49057a516b3db/bukkit/src/main/java/com/griefdefender/configuration/ClaimStorageData.java
IO shouldn't be done on main.

**Comment by bloodmc** [comment] 2021-09-02 02:58
Fixed in 2.0.1 DEV12

**Comment by bloodmc** [comment] 2021-09-02 03:43
Actually turns out, this was caused by bug in Configurate which was fixed in commit
https://github.com/SpongePowered/Configurate/commit/ca3d6245c05a441c988865bcd581771a3640d3f0
I'll update to latest for next dev

**Comment by bloodmc** [comment] 2021-09-02 04:22
Fixed in 2.0.1 DEV12

**Closed as completed by bloodmc** 2021-09-02 04:22 UTC
